name: Tags

on:
  push:
    tags: v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install & publish
        run: |
          npm ci
          echo "registry=https://npm.pkg.github.com/amplement" > .npmrc
          npm publish